version: '3'

services:
  mysqldb:
    container_name: mysqldb
    network_mode: "host"
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=xpto